# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import function_pb2 as function__pb2


class FunctionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.invoke = channel.unary_unary(
                '/org.proto.Function/invoke',
                request_serializer=function__pb2.FunctionRequest.SerializeToString,
                response_deserializer=function__pb2.FunctionResponse.FromString,
                )


class FunctionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FunctionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.invoke,
                    request_deserializer=function__pb2.FunctionRequest.FromString,
                    response_serializer=function__pb2.FunctionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.proto.Function', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Function(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/org.proto.Function/invoke',
            function__pb2.FunctionRequest.SerializeToString,
            function__pb2.FunctionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
